language: python
dist: xenial
group: travis_latest

git:
  depth: 3
  quiet: true

python:
- 3.7
- 3.6
- 3.5
- 2.7

matrix:
  include:
  - os: linux
    python: 3.7
    install: pip install -e .[tests]
    script: flake8
    after_success:
    - pytest -s gtts/tests/ --cov=gtts --cov-config=setup.cfg
    - coveralls
  - os: osx
    language: sh
    install: pip3 install .[tests]
  - os: windows
    language: sh
    before_install:
    - choco install python3
    - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"


install: pip install .[tests]

script: pytest -v -s gtts/tests/


deploy:
  provider: pypi
  user: pndurette
  password:
    secure: GTbUTja0D/LDnIxLLO4ohTHGugwrnx2nMqAw5n7a9JAsfxCVXz6+vu0fkNBmOSJV0bNsFcoj/Q+lcR1SCNsw2NibWWFLDMoYD/yqP/SrHTSUoTXt+o7H9/qvxR2MDr0t2S5kjAux4bw5uPg8WtYlPpD0VWgWkFCm3JmJG+cG1tA=
  on:
    tags: true
    distributions: sdist
    repo: pndurette/gTTS
    branch: master
    python: '3.6'
